# Generated by Django 6.0.3 on 2026-03-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("community", models.CharField(default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
